VR-update/flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Library

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Library.query.order_by(Library.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

VR-update/flaskblog/posts/routes.py
# Importing required Libraries
from flask import (render_template, url_for, flash,redirect, request, abort, Blueprint, session,jsonify)
from flask import current_app
from flaskblog.models import Library, Experience, Question_option, Conversation, Video, Feedback, Avatar, Dragged_video, Hotspot,Node,Virtuals
from flaskblog.posts.forms import PostForm, ExperienceForm
from flaskblog import db
from flaskblog.users.utils import save_video
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from sqlalchemy import func
import shutil
import time
import os

# Registering post
posts = Blueprint('posts', __name__)

# -------  Function to get images from the Library folders ----------------------------------------
def get_images(directory):
    image_files = []
    for file in os.listdir(directory):
        if file.endswith(('.jpg', '.jpeg', '.png', '.gif')):
            image_files.append(file)
            print(image_files)
    return image_files


# --------- Function to get videos from the Library folders  ----------------------------------------
def get_videos(directory):
    video_files = []
    for file in os.listdir(directory):
        if file.endswith(('mp4', 'avi', 'mov', 'mkv', 'wmv')):
            video_files.append(file)
            print(video_files)
    return video_files


# ---------- Restriction and allowing particular format for Image uploads and save -------------------
def allowed_file_img(filename):
    ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# ---------- Restriction and allowing particular format for video uploads and save -------------------
def allowed_video(filename):
    ALLOWED_EXTENSIONS = {'mp4', 'avi', 'mov', 'mkv', 'wmv'}
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# ----------- Route for the new library to create libary and update the database ----------------------
# ----------- This page is for Create library ---------------------------------------------------------
@posts.route("/Library/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        try:
            post = Library(title=form.title.data,
                           content=form.content.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            sanitized_title = secure_filename(post.title)
            flash('Your Library has been created!', 'success')  # Notification for Library created after saving to database
            
            # Construct the full path to the target directory
            target_path = os.path.join(
                current_app.root_path, 'static', "Library")
            
            # Create the directory folder with the Library name
            if not os.path.exists(target_path):
                os.mkdir(target_path)
            target_path = os.path.join(
                current_app.root_path, 'static', "Library", sanitized_title)
            os.mkdir(target_path)
        except FileExistsError:
            print("Folder 'for_CHECK' already exists.")
        return redirect(url_for('main.home'))
    # Renders the create library page
    return render_template('create_Library.html', title='New Library', form=form, legend='Create a New Library')

# ----------- Route for the Existing library to view libaries ----------------------------------------------
# ----------- This page Updates library, Creates Experiences and deletes the current library ---------------
@posts.route("/Library/existing", methods=['GET', 'POST'])
@login_required
def existing_experience():
    page = request.args.get('page', 1, type=int)
    posts = Library.query.order_by(
        Library.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('existing_libraries.html', posts=posts, legend='Existing Libraries')

# ----------- Route for the Existing library to modify libaries and link for Create Experience -------------
# ----------- This page Updates library, Creates Experiences and deletes the current library ---------------
@posts.route("/Library/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Library.query.get_or_404(post_id)
    current_post = Experience.query.filter(Experience.post_id == post_id)
    expId = request.form.get('eid', type=int)
    if (expId != None):
        dele = Experience.query.filter(Experience.eid == expId).first()
        conversations = Conversation.query.filter(
            Conversation.experience_id == expId).all()
        for conversation in conversations:
            db.session.delete(conversation)
        db.session.delete(dele)
        db.session.commit()
    return render_template('Library.html', title=post.title, post=post, experiences=current_post)

# ----------- Route for the Existing library to Update current libaries --------------------------------------
# ----------- This page Updates the current library ----------------------------------------------------------
@posts.route("/Library/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Library.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your Library has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_Library.html', title='Update Post',
                           form=form, legend='Update Post')

# ----------- Route for the Delete of Existing library ------------------------------------------------------
# ----------- This page Deletes the current library and returns to home page --------------------------------
@posts.route("/Library/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Library.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    # Delete related experiences and conversations
    experiences = Experience.query.filter_by(post_id=post_id).all()
    for experience in experiences:
        # Delete related conversations
        conversations = Conversation.query.filter_by(
            experience_id=experience.eid).all()
        for conversation in conversations:
            db.session.delete(conversation)

        db.session.delete(experience)

    db.session.delete(post)
    db.session.commit()
    flash('Your Library has been deleted!', 'success')
    return redirect(url_for('main.home'))

# ----------- Route for Creating new experience based on the Library ID ------------------------------------------------------
# ----------- This page gives option for creating diffrent Experiences -------------------------------------------------------

@posts.route("/experience/new/<int:post_id>", methods=['GET', 'POST'])
@login_required
def new_experience(post_id):
    form = ExperienceForm()
    if form.validate_on_submit():
        experience = Experience(
            etitle=form.etitle.data, econtent=form.econtent.data, user_id=current_user.id, post_id=post_id)
        db.session.add(experience)
        db.session.commit()
        flash('Your experience has been created!', 'success')
        return redirect(url_for('main.home'))
    elif form.virtual_tour.data:
        text_type = "Virtualtour"
        experience = Experience(etitle=form.etitle.data, econtent=form.econtent.data,
                                user_id=current_user.id, post_id=post_id, ex_type=text_type)
        db.session.add(experience)
        db.session.commit()
        return redirect(url_for('posts.virtualtour'))
    elif form.switching_perspective.data:
        text_type = "Switching"
        experience = Experience(etitle=form.etitle.data, econtent=form.econtent.data,
                                user_id=current_user.id, post_id=post_id, ex_type=text_type)
        db.session.add(experience)
        db.session.commit()
        return redirect(url_for('posts.switching'))
    elif form.conversation.data:
        text_type = "Conversation"
        library_instance = Library.query.get(post_id)
        experience_instance = Experience(etitle=form.etitle.data, econtent=form.econtent.data,
                                         user_id=current_user.id, post_id=post_id, ex_type=text_type)
        db.session.add(experience_instance)
        db.session.commit()
        late_ex = db.session.query(func.max(Experience.eid)).scalar()
        current_library = db.session.query(Experience.post_id).filter(
            Experience.eid == late_ex).scalar()
        conversation = Conversation(
            library_id=current_library, experience_id=late_ex)
        db.session.add(conversation)
        db.session.commit()
        late_con = db.session.query(func.max(Conversation.id)).scalar()
        con = Experience.query.filter_by(eid=late_ex, post_id=current_library)
        return redirect(url_for('posts.conversation', con=con, late_con=late_con, questions=None, optionCount=0, optionCountO=0, new=1))
    return render_template('create_experience.html', title='New Experience', form=form, legend='New Experience')

#  -------------------------------------------------------------------------------------------------------------------------------------------------  #



# ----------- Route for Creating new experience based on the Library ID ------------------------------------------------------
# ----------- This page gives option for creating diffrent Experiences -------------------------------------------------------

@posts.route('/virtualtour', methods=['GET', 'POST'])
@login_required
def virtualtour():
    
    
    

VR-update/flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Library
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email,save_video
import os

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
        
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        if form.video.data:
            video_file = save_video(form.video.data)
            current_user.video_file = video_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
     
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Library.query.filter_by(author=user)\
        .order_by(Library.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

VR-update/flaskblog/templates/Library.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    
    <div class="media-body">
      
       <div style="border-bottom: 1px solid #e3e3e3;">
        <center>

        <h2 class="article-title">Library: {{ post.title }}</h2>
      <p class="article-content" >Description: {{ post.content }}</p> {% if post.author == current_user %}{% endif %}
        <h4>Choose the Experience that you want to edit or create a new one.</h4>
      </center>
       </div> 
      <h1 style="margin-left: 20px;">Experience List</h1>
        <ul>
            {% for experience in experiences %}
            <li><form  action="{{ url_for('posts.post', post_id=post.id,exp_id=exper_id ) }}" method="POST">
                {%if experience.ex_type =='Conversation' %}
                <a style="display: inline-block;" href=" {{ url_for('posts.conversationlist',library_id=post.id,experience_id=experience.eid) }}">{{ experience.etitle }} - {{ experience.ex_type }}</a>
                <button type="submit" name="eid" class="btn btn-danger btn-sm m-1" value='{{experience.eid}}'>Delete</button>
                {%elif experience.ex_type =='Switching' %}
                <a style="display: inline-block;" href=" {{ url_for('posts.switchinglist',library_id=post.id,experience_id=experience.eid) }}">{{ experience.etitle }} - {{ experience.ex_type }}</a>
                <button type="submit" name="eid" class="btn btn-danger btn-sm m-1" value='{{experience.eid}}'>Delete</button>
                {%elif  experience.ex_type =='Virtualtour' %}
                <a style="display: inline-block;" href=" {{ url_for('posts.virtualtourlist',library_id=post.id,experience_id=experience.eid) }}">{{ experience.etitle }} - {{ experience.ex_type }}</a>
                <button type="submit" name="eid" class="btn btn-danger btn-sm m-1" value='{{experience.eid}}'>Delete</button>
                {% endif %}
              </form></li>
            {% endfor %}
        </ul>
        <center>
          <div style=" margin-top: 10px;">
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update Library</a>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.new_experience', post_id=post.id) }}">Create New Experience</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        </center>
        
    </div>
    
    <script>
      
    </script>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

VR-update/flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

VR-update/flaskblog/templates/create_experience.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group" style="text-align:center;">
                {{ form.etitle.label(class="form-control-label") }}
                {% if form.etitle.errors %}
                    {{ form.etitle(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.etitle.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.etitle(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group" style="text-align:center;">
                {{ form.econtent.label(class="form-control-label") }}
                {% if form.econtent.errors %}
                    {{ form.econtent(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.econtent.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.econtent(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div style="text-align:center;">
            <h4 style="text-align:center;">Type of Experience:</h4>
            <br>
            {{ form.virtual_tour(class="btn btn-outline-info mr-2") }}
            {{ form.switching_perspective(class="btn btn-outline-info mr-2") }}
            {{ form.conversation(class="btn btn-outline-info mr-2") }}
            <br>
            <br>
            
        </div>
    </form>
</div>
{% endblock content %}

VR-update/flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>VR Authoring App - {{ title }}</title>
    {% else %}
        <title>VR Authoring App</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">VR_Authoring_App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Create_new_Library</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-9">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

VR-update/flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

VR-update/flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}